/** Static knowledge bank for the Saturday quiz.
 *  Themes follow Grace Ofure's teaching: leverage, real estate, assets,
 *  income streams, sales and money mindset. 5 are drawn each week,
 *  rotating by ISO week so the set stays fresh for ~7 weeks.
 */
export interface BankQuestion {
  id: string;
  question: string;
  options: [string, string, string, string];
  correct: number; // index into options
  explain: string;
}

export const QUIZ_BANK: BankQuestion[] = [
  {
    id: "leverage-1",
    question: "Why does hard work alone rarely create wealth?",
    options: [
      "Because taxes take most of a salary",
      "Because your time is limited, so income capped by hours worked stops scaling",
      "Because hard workers spend more",
      "Because salaries never rise",
    ],
    correct: 1,
    explain: "Trading hours for money caps out. Wealth needs leverage: assets, systems or people working while you sleep.",
  },
  {
    id: "asset-1",
    question: "What is the simplest definition of an asset?",
    options: [
      "Anything expensive you own",
      "Something that puts money INTO your pocket over time",
      "Anything you can sell quickly",
      "Property of any kind",
    ],
    correct: 1,
    explain: "An asset feeds you; a liability eats from you. A car you commute in costs money; a rented-out flat pays you.",
  },
  {
    id: "asset-2",
    question: "You buy a laptop for a freelance business that earns you money monthly. The laptop is best described as…",
    options: ["A liability", "A productive asset (a tool that generates income)", "An expense with no return", "A luxury"],
    correct: 1,
    explain: "The same object can be a liability or an asset depending on whether it produces income.",
  },
  {
    id: "re-1",
    question: "What is the biggest advantage land has over most other investments?",
    options: [
      "It can be carried anywhere",
      "It needs no paperwork",
      "It is scarce, cannot be manufactured, and tends to appreciate long-term",
      "It always doubles every year",
    ],
    correct: 2,
    explain: "Nobody is making more land. Scarcity plus population growth drives long-term appreciation, though location still decides everything.",
  },
  {
    id: "re-2",
    question: "In property, what does 'cash flow' mean?",
    options: [
      "The money left from rent after all expenses each month",
      "The sale price of the property",
      "The mortgage balance",
      "The deposit you paid",
    ],
    correct: 0,
    explain: "Cash flow = rental income minus running costs (mortgage, tax, maintenance). Positive cash flow pays you to hold the asset.",
  },
  {
    id: "re-3",
    question: "What is the difference between investing for cash flow and investing for appreciation?",
    options: [
      "There is no difference",
      "Cash flow pays you regularly now; appreciation pays you once, later, when you sell",
      "Appreciation is guaranteed, cash flow is not",
      "Cash flow only applies to shops",
    ],
    correct: 1,
    explain: "Strong investors often want both, but knowing which one a deal offers keeps expectations honest.",
  },
  {
    id: "re-4",
    question: "Why do investors say 'you make your money when you BUY, not when you sell'?",
    options: [
      "Because sellers pay all the fees",
      "Because buying below market value locks in profit from day one",
      "Because prices never move after buying",
      "Because banks refund good buyers",
    ],
    correct: 1,
    explain: "A disciplined purchase price is the one variable fully in your control. Overpay and no market rise will save the deal.",
  },
  {
    id: "compound-1",
    question: "₦100,000 grows at 10% per year. Roughly how much after 2 years, compounded?",
    options: ["₦120,000", "₦121,000", "₦110,000", "₦200,000"],
    correct: 1,
    explain: "Year 1: 110,000. Year 2: 110,000 + 10% = 121,000. The extra ₦1,000 is interest ON interest — compounding.",
  },
  {
    id: "compound-2",
    question: "Who ends up richer at 60: someone investing small amounts from age 25, or someone investing double from age 45?",
    options: [
      "The one who started at 45, because they invest more",
      "Usually the one who started at 25 — time in the market beats amount",
      "They finish equal",
      "Neither, investing is luck",
    ],
    correct: 1,
    explain: "Compounding rewards time more than size. Starting early is the cheapest advantage you will ever get.",
  },
  {
    id: "streams-1",
    question: "Why do wealthy people build multiple income streams?",
    options: [
      "To impress people",
      "So no single failure can sink them, and surpluses can be reinvested",
      "Because one job is illegal",
      "To avoid all tax",
    ],
    correct: 1,
    explain: "Diversified income is resilience. One stream drying up should be an inconvenience, not a catastrophe.",
  },
  {
    id: "streams-2",
    question: "Which of these is PASSIVE income?",
    options: [
      "Overtime pay",
      "Rental income from a property you own",
      "A weekend side job",
      "A salary bonus",
    ],
    correct: 1,
    explain: "Passive income keeps arriving without trading fresh hours for it. Building it usually takes active work up front.",
  },
  {
    id: "sales-1",
    question: "Why is selling called the most important wealth skill?",
    options: [
      "Because salespeople are the richest people",
      "Because every income — job interviews, deals, businesses — is ultimately someone agreeing to pay for value you communicated",
      "Because it requires no learning",
      "Because it avoids competition",
    ],
    correct: 1,
    explain: "You are always selling: yourself, your product, your vision. Money moves when value is communicated convincingly.",
  },
  {
    id: "sales-2",
    question: "The best response to hearing 'no' from a prospect is to…",
    options: [
      "Give up on selling",
      "Ask questions to understand the objection, then address it or move on gracefully",
      "Lower the price immediately",
      "Argue until they agree",
    ],
    correct: 1,
    explain: "A 'no' is information. Understanding the real objection either saves the deal or saves your time.",
  },
  {
    id: "mindset-1",
    question: "What separates a wealth mindset from a scarcity mindset?",
    options: [
      "Wealth mindset spends more",
      "Scarcity asks 'can I afford it?'; wealth asks 'how can I create the money to afford it?'",
      "Wealth mindset ignores budgets",
      "There is no difference",
    ],
    correct: 1,
    explain: "One question closes the door, the other opens a problem to solve. Problems have solutions; closed doors don't.",
  },
  {
    id: "mindset-2",
    question: "'Solve expensive problems' is a wealth principle because…",
    options: [
      "Expensive problems are easier",
      "Income tracks the size and urgency of the problems you solve for others",
      "Cheap problems are illegal",
      "It sounds impressive",
    ],
    correct: 1,
    explain: "A cleaner and a heart surgeon both work hard. The price difference is the problem they solve, not the effort.",
  },
  {
    id: "mindset-3",
    question: "Delayed gratification builds wealth because…",
    options: [
      "Suffering is noble",
      "Money not consumed today can be planted as assets that pay you for years",
      "Prices always fall if you wait",
      "It impresses mentors",
    ],
    correct: 1,
    explain: "Every naira/euro consumed is gone; every one invested is a seed. Wealthy people plant before they feast.",
  },
  {
    id: "inflation-1",
    question: "Cash sitting idle in a low-interest account during high inflation is…",
    options: [
      "Perfectly safe",
      "Quietly losing buying power every month",
      "Growing in real terms",
      "The best long-term strategy",
    ],
    correct: 1,
    explain: "If inflation is 20% and your account pays 5%, your 'safe' money loses ~15% of its buying power a year. Assets are the shield.",
  },
  {
    id: "debt-1",
    question: "What makes debt 'good debt'?",
    options: [
      "A low interest rate only",
      "It finances an asset whose returns outpace the cost of the debt",
      "It is borrowed from family",
      "All debt is bad",
    ],
    correct: 1,
    explain: "A loan buying a cash-flowing property can build wealth; the same loan buying consumption only builds pressure.",
  },
  {
    id: "budget-1",
    question: "In 'pay yourself first', who is 'yourself'?",
    options: [
      "Your landlord",
      "Your investment and savings accounts, funded BEFORE spending begins",
      "Your favourite shop",
      "Your bills",
    ],
    correct: 1,
    explain: "Invest first, live on the rest. The reverse — invest what's left over — reliably leaves nothing over.",
  },
  {
    id: "risk-1",
    question: "The real meaning of 'don't put all your eggs in one basket' for investors is…",
    options: [
      "Never invest at all",
      "Spread capital across assets so one failure cannot wipe you out",
      "Buy only baskets",
      "Keep everything in cash",
    ],
    correct: 1,
    explain: "Diversification is admitting you can't predict the future — and building a portfolio that doesn't need you to.",
  },
  {
    id: "risk-2",
    question: "Before investing in any deal, the FIRST question to ask is…",
    options: [
      "How fast will I get rich?",
      "Do I understand exactly how this makes money, and what happens if it goes wrong?",
      "Who else has joined?",
      "Is the office impressive?",
    ],
    correct: 1,
    explain: "If you can't explain the deal's engine and its worst case, you're not investing — you're gambling on strangers.",
  },
  {
    id: "coinvest-1",
    question: "Co-investment lets small investors access big deals by…",
    options: [
      "Borrowing from each other at high interest",
      "Pooling funds together so the group can buy assets none could afford alone",
      "Sharing one bank account",
      "Skipping legal paperwork",
    ],
    correct: 1,
    explain: "Pooling capital democratises access — but the structure, agreements and exit terms must be crystal clear.",
  },
  {
    id: "landbank-1",
    question: "'Land banking' means…",
    options: [
      "Storing money under land",
      "Buying land in a growth path early and holding it while development raises its value",
      "A bank that only serves farmers",
      "Renting land to banks",
    ],
    correct: 1,
    explain: "You buy where the city is GOING, not where it already is — then let time and infrastructure do the heavy lifting.",
  },
  {
    id: "network-1",
    question: "Why do mentors and rooms matter for wealth?",
    options: [
      "Rich friends give free money",
      "Proximity to people ahead of you compresses years of trial-and-error into borrowed experience",
      "Networking replaces work",
      "They don't matter",
    ],
    correct: 1,
    explain: "You can pay for lessons with time (mistakes) or humility (mentorship). Humility is cheaper.",
  },
  {
    id: "emergency-1",
    question: "An emergency fund's job is to…",
    options: [
      "Earn the highest possible returns",
      "Keep life's surprises from forcing you to sell investments at the worst moment",
      "Pay for holidays",
      "Impress your bank",
    ],
    correct: 1,
    explain: "3-6 months of expenses in reachable cash means a crisis interrupts your month, not your wealth plan.",
  },
  {
    id: "roi-1",
    question: "You buy a plot for ₦2m and sell for ₦3m two years later. Your total return is…",
    options: ["150%", "50%", "33%", "100%"],
    correct: 1,
    explain: "Profit 1m ÷ cost 2m = 50% total (about 22% a year compounded). Always measure against what you put in.",
  },
  {
    id: "value-1",
    question: "Price is what you pay; value is…",
    options: [
      "The same thing",
      "What the thing is actually worth to its use and income potential",
      "Always higher than price",
      "Whatever the seller says",
    ],
    correct: 1,
    explain: "Deals happen when you can see value the price hasn't caught up with — that gap is where profit lives.",
  },
  {
    id: "skills-1",
    question: "Which investment consistently gives the highest returns first?",
    options: [
      "Foreign currency",
      "Your own skills and financial education",
      "Lottery tickets",
      "Luxury goods",
    ],
    correct: 1,
    explain: "A skill that raises your income 30% outperforms almost any asset — and nobody can repossess it.",
  },
  {
    id: "action-1",
    question: "Knowledge without execution is…",
    options: [
      "Still profitable",
      "Just entertainment — execution is what converts learning into money",
      "The safest strategy",
      "Enough to build wealth",
    ],
    correct: 1,
    explain: "Ten videos watched changes nothing; one lesson applied changes the numbers. (That's why this app tracks actions.)",
  },
  {
    id: "ownership-1",
    question: "Employees earn from salaries; owners earn from…",
    options: [
      "Luck",
      "Equity — owning pieces of businesses and assets that grow and pay without a boss's permission",
      "Overtime",
      "Bonuses only",
    ],
    correct: 1,
    explain: "Salaries fund your life. Ownership funds your freedom. The move is converting earned income into owned assets.",
  },
  {
    id: "duediligence-1",
    question: "In Nigerian land purchases, verifying the title/'papers' before paying protects you from…",
    options: [
      "High rent",
      "Buying land the seller doesn't actually own or that's under government acquisition",
      "Slow appreciation",
      "Bad neighbours",
    ],
    correct: 1,
    explain: "Due diligence — titles, surveys, ownership history — is unglamorous and non-negotiable. No papers, no payment.",
  },
  {
    id: "consistency-1",
    question: "Which behaviour builds wealth most reliably?",
    options: [
      "One giant risky bet",
      "Small, boring, consistent investing over years",
      "Waiting for the perfect moment",
      "Copying whatever is trending",
    ],
    correct: 1,
    explain: "Consistency compounds. The 'boring' investor who never stops usually beats the brilliant one who starts and stops.",
  },
  {
    id: "lifestyle-1",
    question: "'Lifestyle inflation' is the trap of…",
    options: [
      "Prices rising in shops",
      "Raising your spending every time your income rises, so wealth never accumulates",
      "Buying too many groceries",
      "Living below your means",
    ],
    correct: 1,
    explain: "If every raise is consumed, you're running on a treadmill dressed as progress. Widen the gap; invest the gap.",
  },
  {
    id: "vision-1",
    question: "Why write financial goals down with numbers and dates?",
    options: [
      "Paper is lucky",
      "A measurable target turns vague wishes into decisions you can actually make daily",
      "Banks require it",
      "It guarantees success",
    ],
    correct: 1,
    explain: "'I want to be rich' gives your brain nothing to do. '₦5m invested by December' tells you what today must look like.",
  },
  {
    id: "give-1",
    question: "Generosity fits inside a wealth plan because…",
    options: [
      "It reduces all taxes to zero",
      "Wealth with purpose sustains motivation, relationships and reputation — the soil money grows in",
      "It replaces investing",
      "It doesn't fit",
    ],
    correct: 1,
    explain: "Money is a tool, not the destination. Builders who know their 'why' outlast builders who only know their 'how much'.",
  },
  {
    id: "fear-1",
    question: "The most expensive financial decision most people make is…",
    options: [
      "Investing too early",
      "Never starting — waiting in fear while time (their biggest asset) drains away",
      "Asking questions",
      "Reading too many books",
    ],
    correct: 1,
    explain: "Mistakes can be corrected and even profited from. Years of doing nothing can't be bought back at any price.",
  },
  {
    id: "team-1",
    question: "'If you want to go fast, go alone; if you want to go far…'",
    options: [
      "…stay home",
      "…go together — teams, partners and communities carry wealth further than lone effort",
      "…go faster",
      "…take a loan",
    ],
    correct: 1,
    explain: "Every big deal has a team behind it: lawyers, agents, partners, mentors, community. Build yours deliberately.",
  },
];
